name: go-ci
on: [pull_request]
env:
  go_version: ^1.19
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}
        id: go
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          make build
          make test
  go_mod_tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}
        id: go
      - uses: actions/checkout@v3
      - run: |
          go mod tidy
          git diff -s --exit-code go.sum
