name: go-ci

on: [push, pull_request]

env:
  go_version: ^1.19

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}
        id: go
      - name: check out
        uses: actions/checkout@v2
      - name: check_go_mod_tidy
        uses: evantorrie/mott-the-tidier@v1-beta
      - name: cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: build_and_test
        run: |
          make build
          make test
